version: "3.8"
services:
  web:
    build: ./my-app
    depends_on:
      - api
    ports:
      - "3000:3000"
    stdin_open: true
    networks:
       - network-backend
  api:
    build: ./api
    # depends_on:
    #   - mongo
    ports:
      - "4000:4000"
    networks: 
      - network-backend

networks:
  network-backend:
